In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data/HM_Water.csv", index_col="Station")
df

,CrW,CrR,NiW,NiR,CuW,CuR,AsW,AsR,CdW,CdR,PbW,PbR
Station,,,,,,,,,,,,
S-1,0.32,0.23,0.13,0.11,1.97,1.55,0.53,0.43,0.015,0.009,0.09,0.06
S-2,0.30,0.24,0.12,0.10,1.58,1.50,0.50,0.45,0.012,0.010,0.08,0.05
S-3,0.31,0.27,0.15,0.12,1.71,1.53,0.47,0.46,0.019,0.012,0.10,0.08
S-4,0.33,0.30,0.11,0.10,1.32,1.10,0.32,0.30,0.025,0.017,0.12,0.10
S-5,0.35,0.29,0.16,0.13,0.90,0.81,0.45,0.43,0.020,0.013,0.15,0.12
S-6,0.29,0.23,0.14,0.12,0.83,0.72,0.41,0.29,0.017,0.011,0.09,0.08
S-7,0.25,0.20,0.12,0.10,1.45,1.15,0.39,0.34,0.012,0.009,0.07,0.05
S-8,0.13,0.10,0.39,0.35,2.15,1.97,0.21,0.15,0.028,0.021,0.19,0.15
S-9,0.11,0.10,0.47,0.41,2.36,2.10,0.18,0.14,0.021,0.016,0.21,0.20
S-10,0.15,0.12,0.59,0.53,2.10,1.54,0.23,0.20,0.027,0.023,0.20,0.15
S-11,0.26,0.22,0.23,0.19,1.97,1.23,0.50,0.47,0.038,0.032,0.15,0.12
S-12,0.29,0.24,0.19,0.12,1.90,1.40,0.45,0.33,0.031,0.023,0.18,0.15
S-13,0.13,0.10,0.09,0.09,2.19,2.10,0.10,0.10,0.009,0.006,0.03,0.02
S-14,0.11,0.10,0.09,0.09,2.45,2.17,0.10,0.10,0.008,0.006,0.08,0.06
S-15,0.18,0.15,0.57,0.45,3.87,3.31,0.27,0.19,0.017,0.011,0.12,0.10
S-16,0.17,0.13,0.63,0.60,3.80,3.29,0.29,0.25,0.012,0.009,0.10,0.09
S-17,0.15,0.11,0.97,0.80,1.18,0.90,0.36,0.30,0.013,0.010,0.15,0.12

In [4]:
df.columns

Index(['CrW', 'CrR', 'NiW', 'NiR', 'CuW', 'CuR', 'AsW', 'AsR', 'CdW', 'CdR',
       'PbW', 'PbR'],
      dtype='object')

In [140]:
param_adult= {
    "IR" : 2.5,
    "EF": 365,
    "ED": 70,
    "BW": 70,
    "AT": 365 * 70,
    "SA": 18000,
    "ET": 0.58,
    "CF": 10**-3,
    'Kp': {
        "Mn": 0.001,
        "Cr": 0.002,
        "Ni": 0.0002,
        "Cu": 0.001,
        "Zn": 0.0006,
        "As": 0.001,
        "Cd": 0.001,
        "Hg": 0.001,
        "Pb": 0.0001
    },
    'RfDing': {
        "Mn": 0.024,
        "Cr": 0.003,
        "Ni": 0.025,
        "Cu": 0.04,
        "Zn": 0.3,
        "As": 0.0003,
        "Cd": 0.0005,
        "Hg": 0.00016,
        "Pb": 0.0035
    },
    "RfDderm": {
        "Mn": 0.00096,
        "Cr": 0.0195,
        "Ni": 0.0054,
        "Cu": 0.04,
        "Zn": 0.06,
        "As": 0.0003,
        "Cd": 0.000025,
        "Hg": 0.00016,
        "Pb": 0.042
        
    },
    "CSFing": {
        "Cd": 0.38,
        "Cr": 0.5,
        "As": 1.5,
        "Pb": 0.0085,
        "Ni": 1.7,
        "Cu": 1.7
    },
    "CSFderm": {
        "Cd": 0.38,
        "Cr": 0.5,
        "As": 1.5,
        "Pb": 0.0085,
        "Ni": 1.7,
        "Cu": 42.5
    }
    

}

param_child= {
    "IR" : 0.64,
    "EF": 365,
    "ED": 6,
    "BW": 25,
    "AT": 365 * 6,
    "SA": 6600,
    "ET": 1,
    "CF": 10**-3,
    'Kp': {
        "Mn": 0.001,
        "Cr": 0.002,
        "Ni": 0.0002,
        "Cu": 0.001,
        "Zn": 0.0006,
        "As": 0.001,
        "Cd": 0.001,
        "Hg": 0.001,
        "Pb": 0.0001
    },
    'RfDing': {
        "Mn": 0.024,
        "Cr": 0.003,
        "Ni": 0.025,
        "Cu": 0.04,
        "Zn": 0.3,
        "As": 0.0003,
        "Cd": 0.0005,
        "Hg": 0.00016,
        "Pb": 0.0035
    },
    "RfDderm": {
        "Mn": 0.00096,
        "Cr": 0.0195,
        "Ni": 0.0054,
        "Cu": 0.04,
        "Zn": 0.06,
        "As": 0.0003,
        "Cd": 0.000025,
        "Hg": 0.00016,
        "Pb": 0.042
    },
    "CSFing": {
        "Cd": 0.38,
        "Cr": 0.5,
        "As": 1.5,
        "Pb": 0.0085,
        "Ni": 1.7,
        "Cu": 1.7
    },
    "CSFderm": {
        "Cd": 0.38,
        "Cr": 0.5,
        "As": 1.5,
        "Pb": 0.0085,
        "Ni": 1.7,
        "Cu": 42.5
    }
    

}

# Shill Method Child Adult

## Winter adult

In [141]:
shil = pd.DataFrame(data={
    "Cd": df.CdW,
    "Cr": df.CrW,
    "Ni": df.NiW,
    "Cu": df.CuW,
    "As": df.AsW,
    "Pb": df.PbW,
})

Cr = (shil["Cr"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
Ni = (shil["Ni"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
Cu = (shil["Cu"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
As = (shil["As"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
Cd = (shil["Cd"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
Pb = (shil["Pb"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])

cdi_ing = pd.DataFrame(data = {
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

hqCr = cdi_ing["Cr"] / param_adult["RfDing"]["Cr"]
hqCu = cdi_ing["Cu"] / param_adult["RfDing"]["Cu"]
hqAs = cdi_ing["As"] / param_adult["RfDing"]["As"]
hqCd = cdi_ing["Cd"] / param_adult["RfDing"]["Cd"]
hqPb = cdi_ing["Pb"] / param_adult["RfDing"]["Pb"]
hqNi = cdi_ing["Ni"] / param_adult["RfDing"]["Ni"]

hq_ingwa = pd.DataFrame(data = {
    "Cr": hqCr,
    "Ni": hqNi,
    "Cu": hqCu,
    "As": hqAs,
    "Cd": hqCd,
    "Pb": hqPb
})

Cr = (shil["Cr"] * param_adult["SA"] * param_adult["Kp"]["Cr"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
Ni = (shil["Ni"] * param_adult["SA"] * param_adult["Kp"]["Ni"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
Cu = (shil["Cu"] * param_adult["SA"] * param_adult["Kp"]["Cu"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
As = (shil["As"] * param_adult["SA"] * param_adult["Kp"]["As"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
Cd = (shil["Cd"] * param_adult["SA"] * param_adult["Kp"]["Cd"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
Pb = (shil["Pb"] * param_adult["SA"] * param_adult["Kp"]["Pb"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])

cdi_derm = pd.DataFrame(data = {
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

hqCr = cdi_derm["Cr"] / param_adult["RfDderm"]["Cr"]
hqCu = cdi_derm["Cu"] / param_adult["RfDderm"]["Cu"]
hqAs = cdi_derm["As"] / param_adult["RfDderm"]["As"]
hqCd = cdi_derm["Cd"] / param_adult["RfDderm"]["Cd"]
hqPb = cdi_derm["Pb"] / param_adult["RfDderm"]["Pb"]
hqNi = cdi_derm["Ni"] / param_adult["RfDderm"]["Ni"]

hq_dermwa = pd.DataFrame(data = {
    "Cr": hqCr,
    "Ni": hqNi,
    "Cu": hqCu,
    "As": hqAs,
    "Cd": hqCd,
    "Pb": hqPb
})

hi = hq_dermwa + hq_ingwa
hiwa = hi.sum(axis=1)

In [181]:
shil = pd.DataFrame(data={
    "Cd": df.CdW,
    "Cr": df.CrW,
    "Ni": df.NiW,
    "Cu": df.CuW,
    "As": df.AsW,
    "Pb": df.PbW,
})

Cr = (shil["Cr"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
Ni = (shil["Ni"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
Cu = (shil["Cu"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
As = (shil["As"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
Cd = (shil["Cd"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])
Pb = (shil["Pb"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"])/ (param_adult["BW"]* param_adult["AT"])

cdi_ing = pd.DataFrame(data = {
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

Cr = (shil["Cr"] * param_adult["SA"] * param_adult["Kp"]["Cr"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
Ni = (shil["Ni"] * param_adult["SA"] * param_adult["Kp"]["Ni"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
Cu = (shil["Cu"] * param_adult["SA"] * param_adult["Kp"]["Cu"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
As = (shil["As"] * param_adult["SA"] * param_adult["Kp"]["As"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
Cd = (shil["Cd"] * param_adult["SA"] * param_adult["Kp"]["Cd"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])
Pb = (shil["Pb"] * param_adult["SA"] * param_adult["Kp"]["Pb"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"])/ (param_adult["BW"]* param_adult["AT"])

cdi_derm = pd.DataFrame(data = {
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

Cd = cdi_ing.Cd * param_adult["CSFing"]["Cd"]
Cr = cdi_ing.Cr * param_adult["CSFing"]["Cr"]
As = cdi_ing.As * param_adult["CSFing"]["As"]
Pb = cdi_ing.Pb * param_adult["CSFing"]["Pb"]
Ni = cdi_ing.Ni * param_adult["CSFing"]["Ni"]
Cu = cdi_ing.Cu * param_adult["CSFing"]["Cu"]

ilcr_ingwa = pd.DataFrame(data={
    "Cd": Cd,
    "Cr": Cr,
    "As": As,
    "Pb": Pb,
    "Ni": Ni,
    "Cu": Cu
})

Cd = cdi_derm.Cd * param_adult["CSFderm"]["Cd"]
Cr = cdi_derm.Cr * param_adult["CSFderm"]["Cr"]
As = cdi_derm.As * param_adult["CSFderm"]["As"]
Pb = cdi_derm.Pb * param_adult["CSFderm"]["Pb"]
Ni = cdi_derm.Ni * param_adult["CSFderm"]["Ni"]
Cu = cdi_derm.Cu * param_adult["CSFderm"]["Cu"]

ilcr_dermwa = pd.DataFrame(data={
    "Cd": Cd,
    "Cr": Cr,
    "As": As,
    "Pb": Pb,
    "Ni": Ni,
    "Cu": Cu
})

ilcr = ilcr_ingwa + ilcr_dermwa
ilcr_wadult = ilcr.sum(axis=1)

## Summer Adult

In [143]:
shil = pd.DataFrame(data={
    "Cd": df.CdR,
    "Cr": df.CrR,
    "Ni": df.NiR,
    "Cu": df.CuR,
    "As": df.AsR,
    "Pb": df.PbR,
})

Cr = (shil["Cr"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
Ni = (shil["Ni"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
Cu = (shil["Cu"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
As = (shil["As"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
Cd = (shil["Cd"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
Pb = (shil["Pb"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])

cdi_ing = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

Cr = (shil["Cr"] * param_adult["SA"] * param_adult["Kp"]["Cr"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
Ni = (shil["Ni"] * param_adult["SA"] * param_adult["Kp"]["Ni"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
Cu = (shil["Cu"] * param_adult["SA"] * param_adult["Kp"]["Cu"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
As = (shil["As"] * param_adult["SA"] * param_adult["Kp"]["As"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
Cd = (shil["Cd"] * param_adult["SA"] * param_adult["Kp"]["Cd"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
Pb = (shil["Pb"] * param_adult["SA"] * param_adult["Kp"]["Pb"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])

cdi_derm = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

hqCr = cdi_ing["Cr"] / param_adult["RfDing"]["Cr"]
hqCu = cdi_ing["Cu"] / param_adult["RfDing"]["Cu"]
hqAs = cdi_ing["As"] / param_adult["RfDing"]["As"]
hqCd = cdi_ing["Cd"] / param_adult["RfDing"]["Cd"]
hqPb = cdi_ing["Pb"] / param_adult["RfDing"]["Pb"]
hqNi = cdi_ing["Ni"] / param_adult["RfDing"]["Ni"]

hq_ingsa = pd.DataFrame(data={
    "Cr": hqCr,
    "Ni": hqNi,
    "Cu": hqCu,
    "As": hqAs,
    "Cd": hqCd,
    "Pb": hqPb
})

hqCr = cdi_derm["Cr"] / param_adult["RfDderm"]["Cr"]
hqCu = cdi_derm["Cu"] / param_adult["RfDderm"]["Cu"]
hqAs = cdi_derm["As"] / param_adult["RfDderm"]["As"]
hqCd = cdi_derm["Cd"] / param_adult["RfDderm"]["Cd"]
hqPb = cdi_derm["Pb"] / param_adult["RfDderm"]["Pb"]
hqNi = cdi_derm["Ni"] / param_adult["RfDderm"]["Ni"]

hq_dermsa = pd.DataFrame(data={
    "Cr": hqCr,
    "Ni": hqNi,
    "Cu": hqCu,
    "As": hqAs,
    "Cd": hqCd,
    "Pb": hqPb
})

hi = hq_dermsa + hq_ingsa
hisa = hi.sum(axis=1)

In [182]:
shil = pd.DataFrame(data={
    "Cd": df.CdR,
    "Cr": df.CrR,
    "Ni": df.NiR,
    "Cu": df.CuR,
    "As": df.AsR,
    "Pb": df.PbR,
})

Cr = (shil["Cr"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
Ni = (shil["Ni"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
Cu = (shil["Cu"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
As = (shil["As"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
Cd = (shil["Cd"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])
Pb = (shil["Pb"] * param_adult["IR"] * param_adult["EF"] * param_adult["ED"]) / (param_adult["BW"] * param_adult["AT"])

cdi_ing = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

Cr = (shil["Cr"] * param_adult["SA"] * param_adult["Kp"]["Cr"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
Ni = (shil["Ni"] * param_adult["SA"] * param_adult["Kp"]["Ni"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
Cu = (shil["Cu"] * param_adult["SA"] * param_adult["Kp"]["Cu"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
As = (shil["As"] * param_adult["SA"] * param_adult["Kp"]["As"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
Cd = (shil["Cd"] * param_adult["SA"] * param_adult["Kp"]["Cd"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])
Pb = (shil["Pb"] * param_adult["SA"] * param_adult["Kp"]["Pb"] * param_adult["ET"] * param_adult["EF"] * param_adult["ED"] * param_adult["CF"]) / (param_adult["BW"] * param_adult["AT"])

cdi_derm = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

Cd = cdi_ing.Cd * param_adult["CSFing"]["Cd"]
Cr = cdi_ing.Cr * param_adult["CSFing"]["Cr"]
As = cdi_ing.As * param_adult["CSFing"]["As"]
Pb = cdi_ing.Pb * param_adult["CSFing"]["Pb"]
Ni = cdi_ing.Ni * param_adult["CSFing"]["Ni"]
Cu = cdi_ing.Cu * param_adult["CSFing"]["Cu"]

ilcr_ingsa = pd.DataFrame(data={
    "Cd": Cd,
    "Cr": Cr,
    "As": As,
    "Pb": Pb,
    "Ni": Ni, 
    "Cu": Cu
})

Cd = cdi_derm.Cd * param_adult["CSFderm"]["Cd"]
Cr = cdi_derm.Cr * param_adult["CSFderm"]["Cr"]
As = cdi_derm.As * param_adult["CSFderm"]["As"]
Pb = cdi_derm.Pb * param_adult["CSFderm"]["Pb"]
Ni = cdi_derm.Ni * param_adult["CSFderm"]["Ni"]
Cu = cdi_derm.Cu * param_adult["CSFderm"]["Cu"]

ilcr_dermsa = pd.DataFrame(data={
    "Cd": Cd,
    "Cr": Cr,
    "As": As,
    "Pb": Pb,
    "Ni": Ni,
    "Cu": Cu
})

ilcr = ilcr_ingsa + ilcr_dermsa
ilcr_sadult = ilcr.sum(axis=1)

## Summer Child

In [145]:
shil = pd.DataFrame(data={
    "Cd": df.CdR,
    "Cr": df.CrR,
    "Ni": df.NiR,
    "Cu": df.CuR,
    "As": df.AsR,
    "Pb": df.PbR,
})

Cr = (shil["Cr"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Ni = (shil["Ni"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Cu = (shil["Cu"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
As = (shil["As"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Cd = (shil["Cd"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Pb = (shil["Pb"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])

cdi_ing = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

Cr = (shil["Cr"] * param_child["SA"] * param_child["Kp"]["Cr"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Ni = (shil["Ni"] * param_child["SA"] * param_child["Kp"]["Ni"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Cu = (shil["Cu"] * param_child["SA"] * param_child["Kp"]["Cu"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
As = (shil["As"] * param_child["SA"] * param_child["Kp"]["As"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Cd = (shil["Cd"] * param_child["SA"] * param_child["Kp"]["Cd"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Pb = (shil["Pb"] * param_child["SA"] * param_child["Kp"]["Pb"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])

cdi_derm = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

hqCr = cdi_ing["Cr"] / param_child["RfDing"]["Cr"]
hqCu = cdi_ing["Cu"] / param_child["RfDing"]["Cu"]
hqAs = cdi_ing["As"] / param_child["RfDing"]["As"]
hqCd = cdi_ing["Cd"] / param_child["RfDing"]["Cd"]
hqPb = cdi_ing["Pb"] / param_child["RfDing"]["Pb"]
hqNi = cdi_ing["Ni"] / param_child["RfDing"]["Ni"]

hq_ingsc = pd.DataFrame(data={
    "Cr": hqCr,
    "Ni": hqNi,
    "Cu": hqCu,
    "As": hqAs,
    "Cd": hqCd,
    "Pb": hqPb
})

hqCr = cdi_derm["Cr"] / param_child["RfDderm"]["Cr"]
hqCu = cdi_derm["Cu"] / param_child["RfDderm"]["Cu"]
hqAs = cdi_derm["As"] / param_child["RfDderm"]["As"]
hqCd = cdi_derm["Cd"] / param_child["RfDderm"]["Cd"]
hqPb = cdi_derm["Pb"] / param_child["RfDderm"]["Pb"]
hqNi = cdi_derm["Ni"] / param_child["RfDderm"]["Ni"]

hq_dermsc = pd.DataFrame(data={
    "Cr": hqCr,
    "Ni": hqNi,
    "Cu": hqCu,
    "As": hqAs,
    "Cd": hqCd,
    "Pb": hqPb
})

hi = hq_dermsc + hq_ingsc
hisc = hi.sum(axis=1)

In [183]:
shil = pd.DataFrame(data={
    "Cd": df.CdR,
    "Cr": df.CrR,
    "Ni": df.NiR,
    "Cu": df.CuR,
    "As": df.AsR,
    "Pb": df.PbR,
})

# Calculate Chronic Daily Intake (CDI) for ingestion
Cr = (shil["Cr"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Ni = (shil["Ni"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Cu = (shil["Cu"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
As = (shil["As"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Cd = (shil["Cd"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Pb = (shil["Pb"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])

cdi_ing = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

# Calculate Chronic Daily Intake (CDI) for dermal exposure
Cr = (shil["Cr"] * param_child["SA"] * param_child["Kp"]["Cr"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Ni = (shil["Ni"] * param_child["SA"] * param_child["Kp"]["Ni"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Cu = (shil["Cu"] * param_child["SA"] * param_child["Kp"]["Cu"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
As = (shil["As"] * param_child["SA"] * param_child["Kp"]["As"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Cd = (shil["Cd"] * param_child["SA"] * param_child["Kp"]["Cd"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Pb = (shil["Pb"] * param_child["SA"] * param_child["Kp"]["Pb"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])

cdi_derm = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

# Calculate Incremental Lifetime Cancer Risk (ILCR) for ingestion
Cd = cdi_ing.Cd * param_child["CSFing"]["Cd"]
Cr = cdi_ing.Cr * param_child["CSFing"]["Cr"]
As = cdi_ing.As * param_child["CSFing"]["As"]
Pb = cdi_ing.Pb * param_child["CSFing"]["Pb"]
Ni = cdi_ing.Ni * param_child["CSFing"]["Ni"]
Cu = cdi_ing.Cu * param_child["CSFing"]["Cu"]


ilcr_ingsc = pd.DataFrame(data={
    "Cd": Cd,
    "Cr": Cr,
    "As": As,
    "Pb": Pb,
    "Ni": Ni,
    "Cu": Cu
})

# Calculate Incremental Lifetime Cancer Risk (ILCR) for dermal exposure
Cd = cdi_derm.Cd * param_child["CSFderm"]["Cd"]
Cr = cdi_derm.Cr * param_child["CSFderm"]["Cr"]
As = cdi_derm.As * param_child["CSFderm"]["As"]
Pb = cdi_derm.Pb * param_child["CSFderm"]["Pb"]
Ni = cdi_derm.Ni * param_child["CSFderm"]["Ni"]
Cu = cdi_derm.Cu * param_child["CSFderm"]["Cu"]


ilcr_dermsc = pd.DataFrame(data={
    "Cd": Cd,
    "Cr": Cr,
    "As": As,
    "Pb": Pb,
    "Ni": Ni,
    "Cu": Cu
})

# Combine ILCR ingestion and dermal to calculate total ILCR
ilcr = ilcr_ingsc + ilcr_dermsc
ilcr_schild = ilcr.sum(axis=1)
ilcr_schild

Station
S-1     0.109433
S-2     0.107174
S-3     0.110494
S-4     0.080322
S-5     0.070633
S-6     0.059027
S-7     0.083215
S-8     0.130466
S-9     0.139773
S-10    0.116998
S-11    0.097065
S-12    0.098066
S-13    0.124128
S-14    0.127969
S-15    0.210275
S-16    0.217766
S-17    0.097354
dtype: float64

## Child Winter

In [184]:
shil = pd.DataFrame(data={
    "Cd": df.CdW,
    "Cr": df.CrW,
    "Ni": df.NiW,
    "Cu": df.CuW,
    "As": df.AsW,
    "Pb": df.PbW,
})

# Calculate Chronic Daily Intake (CDI) for ingestion
Cr = (shil["Cr"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Ni = (shil["Ni"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Cu = (shil["Cu"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
As = (shil["As"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Cd = (shil["Cd"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Pb = (shil["Pb"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])

cdi_ing = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

# Calculate Chronic Daily Intake (CDI) for dermal exposure
Cr = (shil["Cr"] * param_child["SA"] * param_child["Kp"]["Cr"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Ni = (shil["Ni"] * param_child["SA"] * param_child["Kp"]["Ni"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Cu = (shil["Cu"] * param_child["SA"] * param_child["Kp"]["Cu"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
As = (shil["As"] * param_child["SA"] * param_child["Kp"]["As"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Cd = (shil["Cd"] * param_child["SA"] * param_child["Kp"]["Cd"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Pb = (shil["Pb"] * param_child["SA"] * param_child["Kp"]["Pb"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])

cdi_derm = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

# Calculate Hazard Quotients (HQ) for ingestion
hqCr = cdi_ing["Cr"] / param_child["RfDing"]["Cr"]
hqCu = cdi_ing["Cu"] / param_child["RfDing"]["Cu"]
hqAs = cdi_ing["As"] / param_child["RfDing"]["As"]
hqCd = cdi_ing["Cd"] / param_child["RfDing"]["Cd"]
hqPb = cdi_ing["Pb"] / param_child["RfDing"]["Pb"]
hqNi = cdi_ing["Ni"] / param_child["RfDing"]["Ni"]

hq_ingwc = pd.DataFrame(data={
    "Cr": hqCr,
    "Ni": hqNi,
    "Cu": hqCu,
    "As": hqAs,
    "Cd": hqCd,
    "Pb": hqPb
})

# Calculate Hazard Quotients (HQ) for dermal exposure
hqCr = cdi_derm["Cr"] / param_child["RfDderm"]["Cr"]
hqCu = cdi_derm["Cu"] / param_child["RfDderm"]["Cu"]
hqAs = cdi_derm["As"] / param_child["RfDderm"]["As"]
hqCd = cdi_derm["Cd"] / param_child["RfDderm"]["Cd"]
hqPb = cdi_derm["Pb"] / param_child["RfDderm"]["Pb"]
hqNi = cdi_derm["Ni"] / param_child["RfDderm"]["Ni"]

hq_dermwc = pd.DataFrame(data={
    "Cr": hqCr,
    "Ni": hqNi,
    "Cu": hqCu,
    "As": hqAs,
    "Cd": hqCd,
    "Pb": hqPb
})

# Combine Hazard Quotients for ingestion and dermal exposures
hi = hq_dermwc + hq_ingwc
hiwc = hi.sum(axis=1)
hiwc

Station
S-1     51.425333
S-2     48.146784
S-3     46.339678
S-4     33.802219
S-5     44.871925
S-6     40.219655
S-7     38.078090
S-8     24.130130
S-9     21.304989
S-10    26.211420
S-11    50.288061
S-12    45.934721
S-13    12.018568
S-14    12.319462
S-15    29.837779
S-16    31.038108
S-17    35.986731
dtype: float64

In [185]:
shil = pd.DataFrame(data={
    "Cd": df.CdW,
    "Cr": df.CrW,
    "Ni": df.NiW,
    "Cu": df.CuW,
    "As": df.AsW,
    "Pb": df.PbW,
})

# Calculate Chronic Daily Intake (CDI) for ingestion
Cr = (shil["Cr"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Ni = (shil["Ni"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Cu = (shil["Cu"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
As = (shil["As"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Cd = (shil["Cd"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])
Pb = (shil["Pb"] * param_child["IR"] * param_child["EF"] * param_child["ED"]) / (param_child["BW"] * param_child["AT"])

cdi_ing = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

# Calculate Chronic Daily Intake (CDI) for dermal exposure
Cr = (shil["Cr"] * param_child["SA"] * param_child["Kp"]["Cr"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Ni = (shil["Ni"] * param_child["SA"] * param_child["Kp"]["Ni"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Cu = (shil["Cu"] * param_child["SA"] * param_child["Kp"]["Cu"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
As = (shil["As"] * param_child["SA"] * param_child["Kp"]["As"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Cd = (shil["Cd"] * param_child["SA"] * param_child["Kp"]["Cd"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])
Pb = (shil["Pb"] * param_child["SA"] * param_child["Kp"]["Pb"] * param_child["ET"] * param_child["EF"] * param_child["ED"] * param_child["CF"]) / (param_child["BW"] * param_child["AT"])

cdi_derm = pd.DataFrame(data={
    "Cr": Cr,
    "Ni": Ni,
    "Cu": Cu,
    "As": As,
    "Cd": Cd,
    "Pb": Pb
})

# Calculate Incremental Lifetime Cancer Risk (ILCR) for ingestion
Cd = cdi_ing.Cd * param_child["CSFing"]["Cd"]
Cr = cdi_ing.Cr * param_child["CSFing"]["Cr"]
As = cdi_ing.As * param_child["CSFing"]["As"]
Pb = cdi_ing.Pb * param_child["CSFing"]["Pb"]
Ni = cdi_ing.Ni * param_child["CSFing"]["Ni"]
Cu = cdi_ing.Cu * param_child["CSFing"]["Cu"]

ilcr_ingwc = pd.DataFrame(data={
    "Cd": Cd,
    "Cr": Cr,
    "As": As,
    "Pb": Pb,
    "Ni": Ni,
    "Cu": Cu
})

# Calculate Incremental Lifetime Cancer Risk (ILCR) for dermal exposure
Cd = cdi_derm.Cd * param_child["CSFderm"]["Cd"]
Cr = cdi_derm.Cr * param_child["CSFderm"]["Cr"]
As = cdi_derm.As * param_child["CSFderm"]["As"]
Pb = cdi_derm.Pb * param_child["CSFderm"]["Pb"]
Ni = cdi_derm.Ni * param_child["CSFderm"]["Ni"]
Cu = cdi_derm.Cu * param_child["CSFderm"]["Cu"]

ilcr_dermwc = pd.DataFrame(data={
    "Cd": Cd,
    "Cr": Cr,
    "As": As,
    "Pb": Pb,
    "Ni": Ni,
    "Cu": Cu
})

# Combine ILCR ingestion and dermal to calculate total ILCR
ilcr = ilcr_ingwc + ilcr_dermwc
ilcr_wchild = ilcr.sum(axis=1)
ilcr

               Cd        Cr        As        Pb        Ni        Cu
Station
S-1      0.000147  0.004180  0.020562  0.000020  0.005669  0.107838
S-2      0.000118  0.003919  0.019398  0.000017  0.005233  0.086489
S-3      0.000187  0.004050  0.018234  0.000022  0.006541  0.093605
S-4      0.000246  0.004311  0.012415  0.000026  0.004797  0.072257
S-5      0.000197  0.004572  0.017458  0.000033  0.006978  0.049266
S-6      0.000167  0.003789  0.015906  0.000020  0.006105  0.045434
S-7      0.000118  0.003266  0.015130  0.000015  0.005233  0.079373
S-8      0.000275  0.001698  0.008147  0.000041  0.017008  0.117691
S-9      0.000206  0.001437  0.006983  0.000046  0.020497  0.129186
S-10     0.000265  0.001960  0.008923  0.000044  0.025730  0.114954
S-11     0.000373  0.003397  0.019398  0.000033  0.010030  0.107838
S-12     0.000305  0.003789  0.017458  0.000039  0.008286  0.104006
S-13     0.000088  0.001698  0.003880  0.000007  0.003925  0.119881
S-14     0.000079  0.001437  0.003880  0.000017  0.003925  0.134113
S-15     0.000167  0.002352  0.010475  0.000026  0.024858  0.211844
S-16     0.000118  0.002221  0.011251  0.000022  0.027474  0.208012
S-17     0.000128  0.001960  0.013967  0.000033  0.042301  0.064593

In [149]:
hi = pd.DataFrame(data={
    "Adult W": hiwa,
    "Child W": hiwc,
    "Adult S": hisa,
    "Child S": hisc,
})

hi

           Adult W    Child W    Adult S    Child S
Station
S-1      71.205162  51.425333  57.002134  41.151308
S-2      66.682182  48.146784  59.428410  42.907122
S-3      64.120467  46.339678  61.497960  44.409109
S-4      46.688576  33.802219  42.905246  31.028172
S-5      62.082097  44.871925  58.004390  41.893059
S-6      55.649211  40.219655  39.894920  28.824920
S-7      52.717655  38.078090  45.410484  32.793169
S-8      33.246847  24.130130  24.547873  17.817862
S-9      29.387442  21.304989  23.678277  17.158759
S-10     36.142783  26.211420  30.790906  22.331299
S-11     69.439360  50.288061  63.884879  46.249402
S-12     63.463972  45.934721  47.048631  34.051909
S-13     16.599357  12.018568  15.826835  11.445133
S-14     17.026895  12.319462  16.297774  11.782991
S-15     41.250153  29.837779  29.986336  21.680892
S-16     42.954072  31.038108  36.860970  26.627950
S-17     49.809958  35.986731  41.127314  29.709997

In [150]:
cr = pd.DataFrame(data={
    "Adult W": ilcr_wadult,
    "Child W": ilcr_wchild,
    "Adult S": ilcr_sadult,
    "Child S": ilcr_schild,
})

cr

          Adult W   Child W   Adult S   Child S
Station
S-1      0.042405  0.030579  0.034098  0.024586
S-2      0.039779  0.028686  0.034757  0.025064
S-3      0.040270  0.029034  0.037087  0.026742
S-4      0.030218  0.021795  0.027879  0.020108
S-5      0.040551  0.029237  0.036467  0.026294
S-6      0.036044  0.025987  0.027208  0.019614
S-7      0.032958  0.023763  0.028106  0.020264
S-8      0.037775  0.027170  0.031469  0.022628
S-9      0.040573  0.029169  0.034524  0.024819
S-10     0.051354  0.036921  0.045484  0.032699
S-11     0.046119  0.033231  0.041263  0.029735
S-12     0.041452  0.029877  0.029725  0.021430
S-13     0.013321  0.009598  0.012737  0.009174
S-14     0.012962  0.009338  0.012749  0.009183
S-15     0.052670  0.037877  0.040447  0.029085
S-16     0.057138  0.041086  0.052399  0.037671
S-17     0.081232  0.058388  0.066904  0.048088

In [151]:
healthRisk = pd.DataFrame(data={
    "SamplingPoint": df.index,
    "HI Adult W": hiwa,
    "HI Child W": hiwc,
    "HI Adult S": hisa,
    "HI Child S": hisc,
    "CR Adult W": ilcr_wadult,
    "CR Child W": ilcr_wchild,
    "CR Adult S": ilcr_sadult,
    "CR Child S": ilcr_schild,
})

healthRisk

,SamplingPoint,HI Adult W,HI Child W,HI Adult S,HI Child S,CR Adult W,CR Child W,CR Adult S,CR Child S
Station,,,,,,,,,
S-1,S-1,71.205162,51.425333,57.002134,41.151308,0.042405,0.030579,0.034098,0.024586
S-2,S-2,66.682182,48.146784,59.428410,42.907122,0.039779,0.028686,0.034757,0.025064
S-3,S-3,64.120467,46.339678,61.497960,44.409109,0.040270,0.029034,0.037087,0.026742
S-4,S-4,46.688576,33.802219,42.905246,31.028172,0.030218,0.021795,0.027879,0.020108
S-5,S-5,62.082097,44.871925,58.004390,41.893059,0.040551,0.029237,0.036467,0.026294
S-6,S-6,55.649211,40.219655,39.894920,28.824920,0.036044,0.025987,0.027208,0.019614
S-7,S-7,52.717655,38.078090,45.410484,32.793169,0.032958,0.023763,0.028106,0.020264
S-8,S-8,33.246847,24.130130,24.547873,17.817862,0.037775,0.027170,0.031469,0.022628
S-9,S-9,29.387442,21.304989,23.678277,17.158759,0.040573,0.029169,0.034524,0.024819
S-10,S-10,36.142783,26.211420,30.790906,22.331299,0.051354,0.036921,0.045484,0.032699
S-11,S-11,69.439360,50.288061,63.884879,46.249402,0.046119,0.033231,0.041263,0.029735
S-12,S-12,63.463972,45.934721,47.048631,34.051909,0.041452,0.029877,0.029725,0.021430
S-13,S-13,16.599357,12.018568,15.826835,11.445133,0.013321,0.009598,0.012737,0.009174
S-14,S-14,17.026895,12.319462,16.297774,11.782991,0.012962,0.009338,0.012749,0.009183
S-15,S-15,41.250153,29.837779,29.986336,21.680892,0.052670,0.037877,0.040447,0.029085
S-16,S-16,42.954072,31.038108,36.860970,26.627950,0.057138,0.041086,0.052399,0.037671
S-17,S-17,49.809958,35.986731,41.127314,29.709997,0.081232,0.058388,0.066904,0.048088

In [152]:
healthRisk.to_csv("data/HealthRisk.csv")

In [153]:
hq_dermsa.describe()

              Cr         Ni         Cu         As         Cd         Pb
count  17.000000  17.000000  17.000000  17.000000  17.000000  17.000000
mean    0.002816   0.001433   0.006222   0.144171   0.083520   0.000036
std     0.001122   0.001223   0.002827   0.063908   0.042342   0.000016
min     0.001530   0.000497   0.002685   0.049714   0.035794   0.000007
25%     0.001683   0.000552   0.004288   0.094457   0.053691   0.000021
50%     0.003059   0.000663   0.005705   0.149143   0.065623   0.000036
75%     0.003671   0.002265   0.007830   0.213771   0.101417   0.000043
max     0.004589   0.004419   0.012342   0.233657   0.190903   0.000071

In [154]:
hq_metals = pd.DataFrame(data={
    "IngMeanWa": hq_ingwa.mean(),
    "IngMeanWc": hq_ingwc.mean(),
    "IngSDWa": hq_ingwa.std(),
    "IngSDWc": hq_ingwc.std(),
    "DermMeanWa": hq_dermwa.mean(),
    "DermMeanWc": hq_dermwc.mean(),
    "DermSDWa": hq_dermwa.std(),
    "DermSDWc":hq_dermwc.std(),
    "IngMeanSa": hq_ingsa.mean(),
    "IngMeanSc": hq_ingsc.mean(),
    "IngSDSa": hq_ingsa.std(),
    "IngSDSc": hq_ingsc.std(),
    "DermMeanSa": hq_dermsa.mean(),
    "DermMeanSc": hq_dermsc.mean(),
    "DermSDSa": hq_dermsa.std(),
    "DermSDSc": hq_dermsc.std(),
    
    
})
hq_metals

,IngMeanWa,IngMeanWc,IngSDWa,IngSDWc,DermMeanWa,DermMeanWc,DermSDWa,DermSDWc,IngMeanSa,IngMeanSc,IngSDSa,IngSDSc,DermMeanSa,DermMeanSc,DermSDSa,DermSDSc
Cr,2.682073,1.922510,1.029364,0.737848,0.003446,0.006100,0.001323,0.002341,2.191877,1.571137,0.872850,0.625659,0.002816,0.004985,0.001122,0.001985
Ni,0.432773,0.310212,0.366720,0.262865,0.001673,0.002962,0.001418,0.002510,0.370588,0.265638,0.316327,0.226743,0.001433,0.002536,0.001223,0.002165
Cu,1.771534,1.269835,0.754379,0.540739,0.007398,0.013095,0.003150,0.005576,1.490021,1.068047,0.677056,0.485314,0.006222,0.011014,0.002827,0.005005
As,40.336134,28.912941,16.671355,11.950028,0.168444,0.298165,0.069620,0.123235,34.523810,24.746667,15.303524,10.969566,0.144171,0.255200,0.063908,0.113124
Cd,1.361345,0.975812,0.597332,0.428167,0.113699,0.201261,0.049889,0.088310,1.000000,0.716800,0.506967,0.363394,0.083520,0.147840,0.042342,0.074950
Pb,1.266507,0.907832,0.521631,0.373905,0.000044,0.000078,0.000018,0.000032,1.020408,0.731429,0.471766,0.338162,0.000036,0.000063,0.000016,0.000029

In [155]:
hq_dermsc.describe()

              Cr         Ni         Cu         As        Cd         Pb
count  17.000000  17.000000  17.000000  17.000000  17.00000  17.000000
mean    0.004985   0.002536   0.011014   0.255200   0.14784   0.000063
std     0.001985   0.002165   0.005005   0.113124   0.07495   0.000029
min     0.002708   0.000880   0.004752   0.088000   0.06336   0.000013
25%     0.002978   0.000978   0.007590   0.167200   0.09504   0.000038
50%     0.005415   0.001173   0.010098   0.264000   0.11616   0.000063
75%     0.006498   0.004009   0.013860   0.378400   0.17952   0.000075
max     0.008123   0.007822   0.021846   0.413600   0.33792   0.000126

In [156]:
hi_dermsc.mean()

0.42163890239172597

In [157]:
hi_dermsc.min(), hi_dermsc.max()

(0.16882026373626374, 0.7675281294261296)

In [158]:
hq_metals.DermMeanSa.round(5)

Cr    0.00282
Ni    0.00143
Cu    0.00622
As    0.14417
Cd    0.08352
Pb    0.00004
Name: DermMeanSa, dtype: float64

In [159]:
hq_dermsa.std()

Cr    0.001122
Ni    0.001223
Cu    0.002827
As    0.063908
Cd    0.042342
Pb    0.000016
dtype: float64

In [160]:
hq_metals.to_csv("data/HQMetals.csv")

In [161]:
hq_dermsa.min(), hq_dermsa.max()

(Cr    0.001530
 Ni    0.000497
 Cu    0.002685
 As    0.049714
 Cd    0.035794
 Pb    0.000007
 dtype: float64,
 Cr    0.004589
 Ni    0.004419
 Cu    0.012342
 As    0.233657
 Cd    0.190903
 Pb    0.000071
 dtype: float64)

In [162]:
hq_dermsc.min(), hq_dermsc.max()

(Cr    0.002708
 Ni    0.000880
 Cu    0.004752
 As    0.088000
 Cd    0.063360
 Pb    0.000013
 dtype: float64,
 Cr    0.008123
 Ni    0.007822
 Cu    0.021846
 As    0.413600
 Cd    0.337920
 Pb    0.000126
 dtype: float64)

In [163]:
hq_dermwa.min(), hq_dermwa.max()

(Cr    0.001683
 Ni    0.000497
 Cu    0.003095
 As    0.049714
 Cd    0.047726
 Pb    0.000011
 dtype: float64,
 Cr    0.005354
 Ni    0.005358
 Cu    0.014430
 As    0.263486
 Cd    0.226697
 Pb    0.000075
 dtype: float64)

In [164]:
hq_dermwc.min(), hq_dermwc.max()

(Cr    0.002978
 Ni    0.000880
 Cu    0.005478
 As    0.088000
 Cd    0.084480
 Pb    0.000019
 dtype: float64,
 Cr    0.009477
 Ni    0.009484
 Cu    0.025542
 As    0.466400
 Cd    0.401280
 Pb    0.000132
 dtype: float64)

In [165]:
hq_ingsa.min(), hq_ingsa.max()

(Cr     1.190476
 Ni     0.128571
 Cu     0.642857
 As    11.904762
 Cd     0.428571
 Pb     0.204082
 dtype: float64,
 Cr     3.571429
 Ni     1.142857
 Cu     2.955357
 As    55.952381
 Cd     2.285714
 Pb     2.040816
 dtype: float64)

In [166]:
hq_ingsc.min(), hq_ingsc.max()

(Cr    0.853333
 Ni    0.092160
 Cu    0.460800
 As    8.533333
 Cd    0.307200
 Pb    0.146286
 dtype: float64,
 Cr     2.560000
 Ni     0.819200
 Cu     2.118400
 As    40.106667
 Cd     1.638400
 Pb     1.462857
 dtype: float64)

In [167]:
hq_ingwa.min(), hq_ingwa.max()

(Cr     1.309524
 Ni     0.128571
 Cu     0.741071
 As    11.904762
 Cd     0.571429
 Pb     0.306122
 dtype: float64,
 Cr     4.166667
 Ni     1.385714
 Cu     3.455357
 As    63.095238
 Cd     2.714286
 Pb     2.142857
 dtype: float64)

In [168]:
hq_ingwc.min(), hq_ingwc.max()

(Cr    0.938667
 Ni    0.092160
 Cu    0.531200
 As    8.533333
 Cd    0.409600
 Pb    0.219429
 dtype: float64,
 Cr     2.986667
 Ni     0.993280
 Cu     2.476800
 As    45.226667
 Cd     1.945600
 Pb     1.536000
 dtype: float64)

In [169]:
ilcr_ingwa.describe()

              Cd         Cr         As         Pb         Ni
count  17.000000  17.000000  17.000000  17.000000  17.000000
mean    0.000259   0.004023   0.018151   0.000038   0.018393
std     0.000113   0.001544   0.007502   0.000016   0.015586
min     0.000109   0.001964   0.005357   0.000009   0.005464
25%     0.000163   0.002679   0.012321   0.000027   0.007286
50%     0.000231   0.004464   0.019286   0.000036   0.009714
75%     0.000339   0.005357   0.024107   0.000046   0.028536
max     0.000516   0.006250   0.028393   0.000064   0.058893

In [170]:
ilcr_wadult

Station
S-1     0.042405
S-2     0.039779
S-3     0.040270
S-4     0.030218
S-5     0.040551
S-6     0.036044
S-7     0.032958
S-8     0.037775
S-9     0.040573
S-10    0.051354
S-11    0.046119
S-12    0.041452
S-13    0.013321
S-14    0.012962
S-15    0.052670
S-16    0.057138
S-17    0.081232
dtype: float64

In [171]:
ilcr_metals = pd.DataFrame(data={
    "IngMeanWa": ilcr_ingwa.mean(),
    "IngMeanWc": ilcr_ingwc.mean(),
    "IngSDWa": ilcr_ingwa.std(),
    "IngSDWc": ilcr_ingwc.std(),
    "DermMeanWa": ilcr_dermwa.mean(),
    "DermMeanWc": ilcr_dermwc.mean(),
    "DermSDWa": ilcr_dermwa.std(),
    "DermSDWc":ilcr_dermwc.std(),
    "IngMeanSa": ilcr_ingsa.mean(),
    "IngMeanSc": ilcr_ingsc.mean(),
    "IngSDSa": ilcr_ingsa.std(),
    "IngSDSc": ilcr_ingsc.std(),
    "DermMeanSa": ilcr_dermsa.mean(),
    "DermMeanSc": ilcr_dermsc.mean(),
    "DermSDSa": ilcr_dermsa.std(),
    "DermSDSc": ilcr_dermsc.std(),
    
    
})
ilcr_metals

,IngMeanWa,IngMeanWc,IngSDWa,IngSDWc,DermMeanWa,DermMeanWc,DermSDWa,DermSDWc,IngMeanSa,IngMeanSc,IngSDSa,IngSDSc,DermMeanSa,DermMeanSc,DermSDSa,DermSDSc
Cd,0.000259,0.000185,0.000113,0.000081,1.080145e-06,1.911981e-06,4.739469e-07,8.389405e-07,0.000190,0.000136,0.000096,0.000069,7.934400e-07,1.404480e-06,4.022477e-07,7.120247e-07
Cr,0.004023,0.002884,0.001544,0.001107,3.360101e-05,5.947765e-05,1.289587e-05,2.282718e-05,0.003288,0.002357,0.001309,0.000938,2.745983e-05,4.860706e-05,1.093507e-05,1.935632e-05
As,0.018151,0.013011,0.007502,0.005378,7.579966e-05,1.341741e-04,3.132881e-05,5.545560e-05,0.015536,0.011136,0.006887,0.004936,6.487714e-05,1.148400e-04,2.875838e-05,5.090564e-05
Pb,0.000038,0.000027,0.000016,0.000011,1.573457e-08,2.785200e-08,6.480532e-09,1.147129e-08,0.000030,0.000022,0.000014,0.000010,1.267714e-08,2.244000e-08,5.861037e-09,1.037471e-08
Ni,0.018393,0.013184,0.015586,0.011172,1.536171e-05,2.719200e-05,1.301710e-05,2.304177e-05,0.015750,0.011290,0.013444,0.009637,1.315440e-05,2.328480e-05,1.122836e-05,1.987548e-05

In [172]:
ilcr_metals.to_csv("data/ILCRMetals.csv")

In [186]:
ilcr_ingwa.min(),  ilcr_ingwa.max()

(Cd    0.000109
 Cr    0.001964
 As    0.005357
 Pb    0.000009
 Ni    0.005464
 Cu    0.050393
 dtype: float64,
 Cd    0.000516
 Cr    0.006250
 As    0.028393
 Pb    0.000064
 Ni    0.058893
 Cu    0.234964
 dtype: float64)

In [174]:
ilcr_ingwc.min(),  ilcr_ingwc.max()

(Cd    0.000078
 Cr    0.001408
 As    0.003840
 Pb    0.000007
 Ni    0.003917
 dtype: float64,
 Cd    0.000370
 Cr    0.004480
 As    0.020352
 Pb    0.000046
 Ni    0.042214
 dtype: float64)

In [175]:
ilcr_ingsa.min(),  ilcr_ingsa.max()

(Cd    0.000081
 Cr    0.001786
 As    0.005357
 Pb    0.000006
 Ni    0.005464
 dtype: float64,
 Cd    0.000434
 Cr    0.005357
 As    0.025179
 Pb    0.000061
 Ni    0.048571
 dtype: float64)

In [176]:
ilcr_ingsc.min(),  ilcr_ingsc.max()

(Cd    0.000058
 Cr    0.001280
 As    0.003840
 Pb    0.000004
 Ni    0.003917
 dtype: float64,
 Cd    0.000311
 Cr    0.003840
 As    0.018048
 Pb    0.000044
 Ni    0.034816
 dtype: float64)

In [187]:
tcr_wa = ilcr_ingwa + ilcr_dermwa
tcr_wa.mean()

Cd    0.000260
Cr    0.004057
As    0.018227
Pb    0.000038
Ni    0.018408
Cu    0.133041
dtype: float64

In [188]:
tcr_wa.describe()

              Cd         Cr         As         Pb         Ni         Cu
count  17.000000  17.000000  17.000000  17.000000  17.000000  17.000000
mean    0.000260   0.004057   0.018227   0.000038   0.018408   0.133041
std     0.000114   0.001557   0.007533   0.000016   0.015599   0.056653
min     0.000109   0.001981   0.005380   0.000009   0.005469   0.055654
25%     0.000164   0.002701   0.012373   0.000027   0.007292   0.097227
50%     0.000232   0.004502   0.019366   0.000036   0.009722   0.132094
75%     0.000341   0.005402   0.024208   0.000046   0.028560   0.146846
max     0.000518   0.006302   0.028511   0.000064   0.058942   0.259495

In [178]:
tcr_wa = ilcr_ingwa + ilcr_dermwa
tcr_wa = tcr_wa.sum(axis=1)

In [43]:
tcr_wa

Station
S-1     0.042405
S-2     0.039779
S-3     0.040270
S-4     0.030218
S-5     0.040551
S-6     0.036044
S-7     0.032958
S-8     0.037775
S-9     0.040573
S-10    0.051354
S-11    0.046119
S-12    0.041452
S-13    0.013321
S-14    0.012962
S-15    0.052670
S-16    0.057138
S-17    0.081232
dtype: float64

In [44]:
tcr_wa.describe()

count    17.000000
mean      0.040989
std       0.015655
min       0.012962
25%       0.036044
50%       0.040551
75%       0.046119
max       0.081232
dtype: float64

In [191]:
tcr_sa = ilcr_ingsa + ilcr_dermsa
tcr_sa.describe()

              Cd         Cr         As         Pb         Ni         Cu
count  17.000000  17.000000  17.000000  17.000000  17.000000  17.000000
mean    0.000191   0.003315   0.015601   0.000030   0.015763   0.111899
std     0.000097   0.001320   0.006915   0.000014   0.013455   0.050846
min     0.000082   0.001801   0.005380   0.000006   0.005469   0.048278
25%     0.000123   0.001981   0.010221   0.000018   0.006076   0.077111
50%     0.000150   0.003601   0.016139   0.000030   0.007292   0.102591
75%     0.000232   0.004322   0.023132   0.000036   0.024914   0.140811
max     0.000436   0.005402   0.025284   0.000061   0.048612   0.221945

In [45]:
tcr_sa = ilcr_ingsa + ilcr_dermsa
tcr_sa = tcr_sa.sum(axis=1)

In [46]:
tcr_sa.describe()

count    17.000000
mean      0.034900
std       0.012983
min       0.012737
25%       0.028106
50%       0.034524
75%       0.040447
max       0.066904
dtype: float64

In [192]:
tcr_wc = ilcr_ingwc + ilcr_dermwc
tcr_wc.describe()

              Cd         Cr         As         Pb         Ni         Cu
count  17.000000  17.000000  17.000000  17.000000  17.000000  17.000000
mean    0.000187   0.002943   0.013145   0.000027   0.013211   0.108611
std     0.000082   0.001130   0.005433   0.000011   0.011195   0.046250
min     0.000079   0.001437   0.003880   0.000007   0.003925   0.045434
25%     0.000118   0.001960   0.008923   0.000020   0.005233   0.079373
50%     0.000167   0.003266   0.013967   0.000026   0.006978   0.107838
75%     0.000246   0.003919   0.017458   0.000033   0.020497   0.119881
max     0.000373   0.004572   0.020562   0.000046   0.042301   0.211844

In [193]:
tcr_wc = ilcr_ingwc + ilcr_dermwc
tcr_wc

               Cd        Cr        As        Pb        Ni        Cu
Station
S-1      0.000147  0.004180  0.020562  0.000020  0.005669  0.107838
S-2      0.000118  0.003919  0.019398  0.000017  0.005233  0.086489
S-3      0.000187  0.004050  0.018234  0.000022  0.006541  0.093605
S-4      0.000246  0.004311  0.012415  0.000026  0.004797  0.072257
S-5      0.000197  0.004572  0.017458  0.000033  0.006978  0.049266
S-6      0.000167  0.003789  0.015906  0.000020  0.006105  0.045434
S-7      0.000118  0.003266  0.015130  0.000015  0.005233  0.079373
S-8      0.000275  0.001698  0.008147  0.000041  0.017008  0.117691
S-9      0.000206  0.001437  0.006983  0.000046  0.020497  0.129186
S-10     0.000265  0.001960  0.008923  0.000044  0.025730  0.114954
S-11     0.000373  0.003397  0.019398  0.000033  0.010030  0.107838
S-12     0.000305  0.003789  0.017458  0.000039  0.008286  0.104006
S-13     0.000088  0.001698  0.003880  0.000007  0.003925  0.119881
S-14     0.000079  0.001437  0.003880  0.000017  0.003925  0.134113
S-15     0.000167  0.002352  0.010475  0.000026  0.024858  0.211844
S-16     0.000118  0.002221  0.011251  0.000022  0.027474  0.208012
S-17     0.000128  0.001960  0.013967  0.000033  0.042301  0.064593

In [47]:
tcr_wc = ilcr_ingwc + ilcr_dermwc
tcr_wc = tcr_wc.sum(axis=1)

In [48]:
tcr_wc.describe()

count    17.000000
mean      0.029514
std       0.011244
min       0.009338
25%       0.025987
50%       0.029169
75%       0.033231
max       0.058388
dtype: float64

In [194]:
tcr_sc = ilcr_ingsc + ilcr_dermsc
tcr_sc.describe()

              Cd         Cr         As         Pb         Ni         Cu
count  17.000000  17.000000  17.000000  17.000000  17.000000  17.000000
mean    0.000138   0.002405   0.011251   0.000022   0.011313   0.091351
std     0.000070   0.000958   0.004987   0.000010   0.009656   0.041510
min     0.000059   0.001306   0.003880   0.000004   0.003925   0.039413
25%     0.000088   0.001437   0.007371   0.000013   0.004361   0.062951
50%     0.000108   0.002613   0.011639   0.000022   0.005233   0.083752
75%     0.000167   0.003135   0.016682   0.000026   0.017880   0.114954
max     0.000315   0.003919   0.018234   0.000044   0.034888   0.181189

In [49]:
tcr_sc = ilcr_ingsc + ilcr_dermsc
tcr_sc = tcr_sc.sum(axis=1)

In [50]:
tcr_sc.describe()

count    17.000000
mean      0.025128
std       0.009324
min       0.009174
25%       0.020264
50%       0.024819
75%       0.029085
max       0.048088
dtype: float64

In [51]:
ilcr_dermsa.min(), ilcr_dermsa.max()

(Cd    3.400457e-07
 Cr    1.491429e-05
 As    2.237143e-05
 Pb    2.535429e-09
 Ni    4.563771e-06
 dtype: float64,
 Cd    1.813577e-06
 Cr    4.474286e-05
 As    1.051457e-04
 Pb    2.535429e-08
 Ni    4.056686e-05
 dtype: float64)

In [52]:
ilcr_dermsc.min(), ilcr_dermsc.max()

(Cd    6.019200e-07
 Cr    2.640000e-05
 As    3.960000e-05
 Pb    4.488000e-09
 Ni    8.078400e-06
 dtype: float64,
 Cd    3.210240e-06
 Cr    7.920000e-05
 As    1.861200e-04
 Pb    4.488000e-08
 Ni    7.180800e-05
 dtype: float64)

In [53]:
ilcr_dermwa.min(), ilcr_dermwa.max()

(Cd    4.533943e-07
 Cr    1.640571e-05
 As    2.237143e-05
 Pb    3.803143e-09
 Ni    4.563771e-06
 dtype: float64,
 Cd    2.153623e-06
 Cr    5.220000e-05
 As    1.185686e-04
 Pb    2.662200e-08
 Ni    4.918731e-05
 dtype: float64)

In [54]:
ilcr_dermwc.min(), ilcr_dermwc.max()

(Cd    8.025600e-07
 Cr    2.904000e-05
 As    3.960000e-05
 Pb    6.732000e-09
 Ni    8.078400e-06
 dtype: float64,
 Cd    3.812160e-06
 Cr    9.240000e-05
 As    2.098800e-04
 Pb    4.712400e-08
 Ni    8.706720e-05
 dtype: float64)

In [55]:
hiwa.describe()

count    17.000000
mean     48.145070
std      17.412093
min      16.599357
25%      36.142783
50%      49.809958
75%      63.463972
max      71.205162
dtype: float64

In [56]:
hi_ingwa = hq_ingwa.sum(axis=1)
hi_ingwa

Station
S-1     70.839201
S-2     66.350850
S-3     63.761480
S-4     46.369728
S-5     61.729422
S-6     55.335629
S-7     52.442262
S-8     32.963180
S-9     29.159524
S-10    35.853912
S-11    68.951446
S-12    63.042687
S-13    16.485289
S-14    16.918112
S-15    40.994133
S-16    42.718027
S-17    49.541327
dtype: float64

In [57]:
hi_ingwa.describe()

count    17.000000
mean     47.850365
std      17.326978
min      16.485289
25%      35.853912
50%      49.541327
75%      63.042687
max      70.839201
dtype: float64

In [58]:
hi_ingwa = hq_ingwa.sum(axis=1)
hi_ingwa.describe()

count    17.000000
mean     47.850365
std      17.326978
min      16.485289
25%      35.853912
50%      49.541327
75%      63.042687
max      70.839201
dtype: float64

In [59]:
hi_dermwa = hq_dermwa.sum(axis=1)
hi_dermwa.describe()

count    17.000000
mean      0.294705
std       0.095527
min       0.108783
25%       0.256020
50%       0.288872
75%       0.352675
max       0.487915
dtype: float64

In [60]:
hi_ingsa = hq_ingsa.sum(axis=1)
hi_ingsa.describe()

count    17.000000
mean     40.596704
std      15.631531
min      15.731463
25%      29.809099
50%      40.909014
75%      56.724745
max      63.451276
dtype: float64

In [61]:
hi_dermsa = hq_dermsa.sum(axis=1)
hi_dermsa.describe()

count    17.000000
mean      0.238199
std       0.082655
min       0.095372
25%       0.195579
50%       0.230637
75%       0.293206
max       0.433604
dtype: float64

In [62]:
hi_ingwc = hq_ingwc.sum(axis=1)
hi_ingwc.describe()

count    17.000000
mean     34.299142
std      12.419978
min      11.816655
25%      25.700084
50%      35.511223
75%      45.188998
max      50.777539
dtype: float64

In [63]:
hi_dermwc = hq_dermwc.sum(axis=1)
hi_dermwc.describe()

count    17.000000
mean      0.521661
std       0.169094
min       0.192559
25%       0.453185
50%       0.511336
75%       0.624276
max       0.863665
dtype: float64

In [64]:
hi_ingsc = hq_ingsc.sum(axis=1)
hi_ingsc.describe()

count    17.000000
mean     29.099717
std      11.204682
min      11.276312
25%      21.367162
50%      29.323581
75%      40.660297
max      45.481874
dtype: float64

In [65]:
hi_dermsc = hq_dermsc.sum(axis=1)
hi_dermsc.describe()

count    17.000000
mean      0.421639
std       0.146309
min       0.168820
25%       0.346197
50%       0.408255
75%       0.519008
max       0.767528
dtype: float64

In [66]:
cr_ingwa = ilcr_ingwa.sum(axis=1)
cr_ingwa.describe()

count    17.000000
mean      0.040864
std       0.015634
min       0.012919
25%       0.035901
50%       0.040388
75%       0.045954
max       0.081079
dtype: float64

In [67]:
cr_dermwa = ilcr_dermwa.sum(axis=1)
cr_dermwa.describe()

count    17.000000
mean      0.000126
std       0.000041
min       0.000044
25%       0.000105
50%       0.000131
75%       0.000160
max       0.000174
dtype: float64

In [68]:
cr_ingsa = ilcr_ingsa.sum(axis=1)
cr_ingsa.describe()

count    17.000000
mean      0.034794
std       0.012966
min       0.012695
25%       0.027994
50%       0.034456
75%       0.040358
max       0.066779
dtype: float64

In [69]:
cr_dermsa = ilcr_dermsa.sum(axis=1)
cr_dermsa.describe()

count    17.000000
mean      0.000106
std       0.000035
min       0.000042
25%       0.000088
50%       0.000111
75%       0.000137
max       0.000150
dtype: float64

In [70]:
cr_ingwc = ilcr_ingwc.sum(axis=1)
cr_ingwc.describe()

count    17.000000
mean      0.029291
std       0.011206
min       0.009260
25%       0.025734
50%       0.028950
75%       0.032940
max       0.058118
dtype: float64

In [71]:
cr_dermwc = ilcr_dermwc.sum(axis=1)
cr_dermwc.describe()

count    17.000000
mean      0.000223
std       0.000072
min       0.000078
25%       0.000186
50%       0.000232
75%       0.000283
max       0.000308
dtype: float64

In [72]:
cr_ingsc = ilcr_ingsc.sum(axis=1)
cr_ingsc.describe()

count    17.000000
mean      0.024940
std       0.009294
min       0.009100
25%       0.020066
50%       0.024698
75%       0.028929
max       0.047867
dtype: float64

In [73]:
cr_dermsc = ilcr_dermsc.sum(axis=1)
cr_dermsc.describe()

count    17.000000
mean      0.000188
std       0.000063
min       0.000075
25%       0.000156
50%       0.000197
75%       0.000242
max       0.000265
dtype: float64

## HI

In [75]:
Hiwa = hi_ingwa + hi_dermwa
Hiwc = hi_ingwc + hi_dermwc
Hisa = hi_ingsa + hi_dermsa
Hisc = hi_ingsc + hi_dermsc

In [76]:
Hiwa

Station
S-1     71.205162
S-2     66.682182
S-3     64.120467
S-4     46.688576
S-5     62.082097
S-6     55.649211
S-7     52.717655
S-8     33.246847
S-9     29.387442
S-10    36.142783
S-11    69.439360
S-12    63.463972
S-13    16.599357
S-14    17.026895
S-15    41.250153
S-16    42.954072
S-17    49.809958
dtype: float64

In [79]:
Hi = pd.DataFrame(data={
    "HIWinterA": Hiwa,
    "HIWinterC": Hiwc,
    "HIRainyA": Hisa,
    "HIRainyC": Hisc,
    
})

In [80]:
Hi

         HIWinterA  HIWinterC   HIRainyA   HIRainyC
Station
S-1      71.205162  51.425333  57.002134  41.151308
S-2      66.682182  48.146784  59.428410  42.907122
S-3      64.120467  46.339678  61.497960  44.409109
S-4      46.688576  33.802219  42.905246  31.028172
S-5      62.082097  44.871925  58.004390  41.893059
S-6      55.649211  40.219655  39.894920  28.824920
S-7      52.717655  38.078090  45.410484  32.793169
S-8      33.246847  24.130130  24.547873  17.817862
S-9      29.387442  21.304989  23.678277  17.158759
S-10     36.142783  26.211420  30.790906  22.331299
S-11     69.439360  50.288061  63.884879  46.249402
S-12     63.463972  45.934721  47.048631  34.051909
S-13     16.599357  12.018568  15.826835  11.445133
S-14     17.026895  12.319462  16.297774  11.782991
S-15     41.250153  29.837779  29.986336  21.680892
S-16     42.954072  31.038108  36.860970  26.627950
S-17     49.809958  35.986731  41.127314  29.709997

In [81]:
Hi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, S-1 to S-17
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   HIWinterA  17 non-null     float64
 1   HIWinterC  17 non-null     float64
 2   HIRainyA   17 non-null     float64
 3   HIRainyC   17 non-null     float64
dtypes: float64(4)
memory usage: 1.2+ KB

In [83]:
Hi.to_csv("data/HISeasonal.csv")

In [84]:
Hi.to_excel("data/HISeasonal.xlsx")

## CR

In [85]:
crwa = cr_ingwa + cr_dermwa
crwc = cr_ingwc + cr_dermwc
crsa = cr_ingsa + cr_dermsa
crsc = cr_ingsc + cr_dermsc

In [86]:
CR = pd.DataFrame(data={
    "CRWinterA": crwa,
    "CRWinterC": crwc,
    "CRRainyA": crsa,
    "CRRainyC": crsc
})

In [87]:
CR

         CRWinterA  CRWinterC  CRRainyA  CRRainyC
Station
S-1       0.042405   0.030579  0.034098  0.024586
S-2       0.039779   0.028686  0.034757  0.025064
S-3       0.040270   0.029034  0.037087  0.026742
S-4       0.030218   0.021795  0.027879  0.020108
S-5       0.040551   0.029237  0.036467  0.026294
S-6       0.036044   0.025987  0.027208  0.019614
S-7       0.032958   0.023763  0.028106  0.020264
S-8       0.037775   0.027170  0.031469  0.022628
S-9       0.040573   0.029169  0.034524  0.024819
S-10      0.051354   0.036921  0.045484  0.032699
S-11      0.046119   0.033231  0.041263  0.029735
S-12      0.041452   0.029877  0.029725  0.021430
S-13      0.013321   0.009598  0.012737  0.009174
S-14      0.012962   0.009338  0.012749  0.009183
S-15      0.052670   0.037877  0.040447  0.029085
S-16      0.057138   0.041086  0.052399  0.037671
S-17      0.081232   0.058388  0.066904  0.048088

In [88]:
CR.to_csv("data/CRGeo.csv")